### ISSUE TITLE
not clear about the  parameter  --rescale_size  nshift，could you please give an example ?

### ISSUE THREAD

**Issue by wbszhu** [Phlya/coolpuppy#13]
Thanks for your wonderful tools ~
I am confused about the parameter --rescale_size and the nshift , even I read the paper Coolpup.py – a versatile tool to perform pile-up analysis of Hi-C data. could you please give some example ?

**Comment by Phlya** [comment]
Hello, and thank you for your interest in coolpuppy!

`--rescale_size` is used for rescaled pileups, e.g. when you are averaging features of different sizes, but want their edges to align. For example, for averaging TADs. This parameter defines the final size of rescaled features, e.g. 99 will rescale all features to 99×99 squares, and the output will be 99×99 pixels.

`--nshifts` determines how many random shifts are used for estimation of background level of interactions. I usually just use `--expected` instead, since it's faster and results are the same, but in some cases (e.g. single cell analysis) you need to use random shifts.

Please let me know whether this helps!

**Comment by Phlya** [comment]
I'll close this, feel free to reopen if still anything is unclear.

**Comment by wbszhu** [comment]
Sorry, it's too late to reply.Thank you very much for your reply, it makes sense to me.
Ruby















At 2019-12-20 22:36:00, "Ilya Flyamer" <notifications@github.com> wrote:

I'll close this, feel free to reopen if still anything is unclear.
