### ISSUE TITLE
json file full of zeros

### ISSUE THREAD

**Issue by cmdoret** [Phlya/coolpuppy#5]
Whenever I try to use the `--save_all` feature, e.g:

```
coolpup.py --maxdist 1000000 \
    --outname chr10_5kb \
    --save_all \
    --by_window \
    chr10_5kb.cool \
    ../peaks.bed 
```
The output json file comes out as empty: all windows are there, but they are filled with 0's.

```
{"chr10:-261-309": [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
```
However, the pileup matrix looks good.
Would you have any idea why this could happen ?
I will try to investigate further when I have time, but any pointer would be appreciated :)

**Comment by Phlya** [comment]
Mhhh I have a suspicion it has something to do with this commit (https://github.com/Phlya/coolpuppy/commit/45209f58406b385d69b2e2f5555e34c36bcebe2e), because your output coordinates are negative and, moreover, look like bin IDs, not peak coordinates... Fixing the output coordinates is easy (https://github.com/Phlya/coolpuppy/blob/f83977337266a5176ca16a94ff338f9846a0f0f6/coolpuppy/coolpup.py#L424), but perhaps this has also broken some computation somewhere - I take it the Enrichment file output is also all zeros or nans?
I will check this tomorrow!


Really need to write tests.

**Comment by Phlya** [comment]
https://github.com/Phlya/coolpuppy/blob/f83977337266a5176ca16a94ff338f9846a0f0f6/coolpuppy/coolpup.py#L402
Yeah, here `m` should be multiplied by `c.binsize`
(or maybe I should just revert that commit back, it didn't really change anything, I just thought it removed some unnecessary complexity...

**Comment by Phlya** [comment]
And here
https://github.com/Phlya/coolpuppy/blob/f83977337266a5176ca16a94ff338f9846a0f0f6/coolpuppy/coolpup.py#L405

**Comment by Phlya** [comment]
Hopefully, this is fixed, but I haven't tested, on a wrong computer right now. Let me know if you have a chance to check, otherwise I'll try tomorrow. Thanks for reporting!

**Comment by cmdoret** [comment]
Yup seems to have worked, thank you !
Tests would good, indeed. If you decide on a framework, I'd be happy to contribute.

**Comment by Phlya** [comment]
Thank you for your offer! Unfortunately, I have exactly zero experience with testing code, so not quite sure how to start, to be honest.
